version: "3.9"

services:
  chrono_gui:
    build:
      context: docker
      dockerfile: tracked_sim.dockerfile
    container_name: chrono_gui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - /usr/lib/nvidia:/usr/lib/nvidia:ro
    stdin_open: true
    tty: true