version: "3.9"

services:
  object314_test:
    build:
      context: .
      dockerfile: docker/object314_chrono.dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - /usr/lib/nvidia:/usr/lib/nvidia:ro
    stdin_open: true
    tty: true
    command: bash -c "cd /usr/local/share/chrono/bin && ./demo_VEH_Marder"